# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .acl import *
from .cluster import *
from .get_cluster import *
from .get_namespace import *
from .get_network import *
from .namespace import *
from .network import *
from .provider import *
from .topic import *
from .user import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_redpanda.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_redpanda.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "redpanda",
  "mod": "index/acl",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/acl:Acl": "Acl"
  }
 },
 {
  "pkg": "redpanda",
  "mod": "index/cluster",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/cluster:Cluster": "Cluster"
  }
 },
 {
  "pkg": "redpanda",
  "mod": "index/namespace",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/namespace:Namespace": "Namespace"
  }
 },
 {
  "pkg": "redpanda",
  "mod": "index/network",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/network:Network": "Network"
  }
 },
 {
  "pkg": "redpanda",
  "mod": "index/topic",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/topic:Topic": "Topic"
  }
 },
 {
  "pkg": "redpanda",
  "mod": "index/user",
  "fqn": "pulumi_redpanda",
  "classes": {
   "redpanda:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "redpanda",
  "token": "pulumi:providers:redpanda",
  "fqn": "pulumi_redpanda",
  "class": "Provider"
 }
]
"""
)
