// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/pulumiverse/pulumi-redpanda/sdk/go/redpanda/internal"
)

var _ = internal.GetEnvOrDefault

// The id for the client. You need clientId AND clientSecret to use this provider
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "redpanda:clientId")
}

// Redpanda client secret. You need clientId AND clientSecret to use this provider
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "redpanda:clientSecret")
}
