// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package redpanda

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumiverse/pulumi-redpanda/sdk/go/redpanda/internal"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "redpanda:index/acl:Acl":
		r = &Acl{}
	case "redpanda:index/cluster:Cluster":
		r = &Cluster{}
	case "redpanda:index/network:Network":
		r = &Network{}
	case "redpanda:index/resourceGroup:ResourceGroup":
		r = &ResourceGroup{}
	case "redpanda:index/serverlessCluster:ServerlessCluster":
		r = &ServerlessCluster{}
	case "redpanda:index/topic:Topic":
		r = &Topic{}
	case "redpanda:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:redpanda" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := internal.PkgVersion()
	if err != nil {
		version = semver.Version{Major: 1}
	}
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/acl",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/cluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/network",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/resourceGroup",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/serverlessCluster",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/topic",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"redpanda",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"redpanda",
		&pkg{version},
	)
}
