name: lint

on:
  workflow_call:
    inputs: {}
  pull_request:
    branches:
    - main
    - v*
    - feature*
    paths-ignore:
    - CHANGELOG.md

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
    - name: Install go
      uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
      with:
        # The versions of golangci-lint and setup-go here cross-depend and need to update together.
        go-version: 1.23
        # Either this action or golangci-lint needs to disable the cache
        cache: false
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@25d5e2dd555cd74f1fab9ac1e6ea117acde2c0c4 # v1.12.0
      with:
        repo: pulumi/pulumictl
    - name: disarm go:embed directives to enable lint
      continue-on-error: true # this fails if there are no go:embed directives
      run: |
        git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'
    - name: prepare upstream
      continue-on-error: true
      run: make upstream
    - run: cd provider && go mod tidy
    - name: golangci-lint
      uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3
      with:
        version: v1.62.0
        working-directory: provider
        skip-pkg-cache: true
