// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data source for a list of Redpanda Cloud serverless regions
 */
export function getServerlessRegions(args: GetServerlessRegionsArgs, opts?: pulumi.InvokeOptions): Promise<GetServerlessRegionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("redpanda:index/getServerlessRegions:getServerlessRegions", {
        "cloudProvider": args.cloudProvider,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessRegions.
 */
export interface GetServerlessRegionsArgs {
    /**
     * Cloud provider where the serverless regions exist
     */
    cloudProvider: string;
}

/**
 * A collection of values returned by getServerlessRegions.
 */
export interface GetServerlessRegionsResult {
    /**
     * Cloud provider where the serverless regions exist
     */
    readonly cloudProvider: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    /**
     * Serverless regions available for the cloud provider
     */
    readonly serverlessRegions: outputs.GetServerlessRegionsServerlessRegion[];
}
/**
 * Data source for a list of Redpanda Cloud serverless regions
 */
export function getServerlessRegionsOutput(args: GetServerlessRegionsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetServerlessRegionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("redpanda:index/getServerlessRegions:getServerlessRegions", {
        "cloudProvider": args.cloudProvider,
    }, opts);
}

/**
 * A collection of arguments for invoking getServerlessRegions.
 */
export interface GetServerlessRegionsOutputArgs {
    /**
     * Cloud provider where the serverless regions exist
     */
    cloudProvider: pulumi.Input<string>;
}
